### ISSUE TITLE
add description for a working example usage

### ISSUE THREAD

**Issue by nandaloo** [laureleya/PrototypeTigramiteGui#5]
I successfully installed the package, and was able to start the GUI.
Then, I just wanted to try out "how it looks", and hence I selected some data, mask and paramters more of less arbitrarily (since I don't actually know what all the options do)
Doing so I just got an error message.

It would be nice to have a description of a configuration in the README that works, i.e. where the UI gives some output and visualizations.

**Comment by ghost** [comment]
Added to README.md
